- source/behavior/entities/format/components/interact.json
Fixed #23 
Fixed an issue with the type being wrong in cooldown_after_being_attacked
Also changed default as there is no default
> Update interact.json 

- source/behavior/entities/format/behaviors/defend_village_target.json
- source/behavior/entities/format/behaviors/eat_block.json
- source/behavior/entities/format/behaviors/find_mount.json
- source/behavior/entities/format/behaviors/harvest_farm_block.json
- source/behavior/entities/format/behaviors/move_to_block.json
- source/behavior/entities/format/behaviors/nap.json
- source/behavior/entities/format/behaviors/random_hover.json
- source/behavior/entities/format/behaviors/send_event.json
- source/behavior/entities/format/behaviors/stalk_and_pounce_on_target.json
- source/behavior/entities/format/behaviors/swim_with_entity.json
- source/behavior/entities/format/behaviors/swoop_attack.json
- source/behavior/entities/format/behaviors/target_when_pushed.json
- source/behavior/entities/format/components/block_sensor.json
- source/behavior/entities/format/components/dweller.json
- source/behavior/entities/format/components/interact.json
- source/behavior/entities/format/components/knockback_resistance.json
- source/behavior/entities/format/components/movement.glide.json
- source/behavior/entities/format/components/projectile.json
- source/behavior/entities/format/components/trade_resupply.json
- source/behavior/entities/format/components/trust.json
Added descriptions for some undocumented properties
Added some tested properties
> Updated descriptions

- source/behavior/entities/format/behaviors/delayed_attack.json
- source/behavior/entities/format/behaviors/door_interact.json
- source/behavior/entities/format/behaviors/lay_egg.json
- source/behavior/entities/format/behaviors/move_to_liquid.json
- source/behavior/entities/format/behaviors/nap.json
- source/behavior/entities/format/behaviors/nearest_attackable_target.json
- source/behavior/entities/format/behaviors/share_items.json
- source/behavior/entities/format/behaviors/stroll_towards_village.json
- source/behavior/entities/format/behaviors/vex_random_move.json
- source/behavior/entities/format/behaviors/wither_target_highest_damage.json
- source/behavior/entities/format/components/bribeable.json
- source/behavior/entities/format/components/exhaustion_values.json
- source/behavior/entities/format/components/leashable.json
- source/behavior/entities/format/components/navigation.fly.json
- source/behavior/entities/format/components/npc.json
- source/behavior/entities/format/components/physics.json
- source/behavior/entities/format/components/transformation.json
Went through and checked every duplicated description and corrected the ones that were incorrect.
> Correct descriptions for entity components

- source/behavior/items/format/components/foil.json
- source/behavior/items/format/minecraft.item.json
Adds `minecraft:foil` item component to the schema.
> Add `minecraft:foil` item component

- source/behavior/spawn_rules/components/biome_filter.json
- source/behavior/spawn_rules/components/brightness_filter.json
- source/behavior/spawn_rules/components/delay_filter.json
- source/behavior/spawn_rules/components/density_limit.json
- source/behavior/spawn_rules/components/difficulty_filter.json
- source/behavior/spawn_rules/components/distance_filter.json
- source/behavior/spawn_rules/components/height_filter.json
- source/behavior/spawn_rules/components/herd.json
- source/behavior/spawn_rules/components/mob_event_filter.json
- source/behavior/spawn_rules/components/permute_type.json
- source/behavior/spawn_rules/components/player_in_village_filter.json
- source/behavior/spawn_rules/components/spawns_lava.json
- source/behavior/spawn_rules/components/spawns_on_block_filter.json
- source/behavior/spawn_rules/components/spawns_on_block_prevented_filter.json
- source/behavior/spawn_rules/components/spawns_on_surface.json
- source/behavior/spawn_rules/components/spawns_underground.json
- source/behavior/spawn_rules/components/spawns_underwater.json
- source/behavior/spawn_rules/components/weight.json
- source/behavior/spawn_rules/components/world_age_filter.json
- Fixes #86
- Fixes #85
- Fixes #84
- Fixes #83
- Fixes #82
- Fixes #81
- Fixes #80
- Fixes #79
- Fixes #77
- Fixes #76
- Fixes #75
- Fixes #73
- Fixes #72
- Fixes #71
- Fixes #70
- Fixes #69
- Fixes #87
> Update documentation for spawn rules

- source/behavior/entities/format/behaviors/avoid_block.json
- source/behavior/entities/format/behaviors/celebrate.json
- source/behavior/entities/format/behaviors/celebrate_survive.json
- source/behavior/entities/format/behaviors/circle_around_anchor.json
- Fixes #91
- Fixes #93
- Fixes #94
- Fixes #97
> Fill defaults in entity behaviors

- CONTRIBUTING.md
- vscode-settings.json
Don't forget Oxford Commas! :)
> Fix minor problems in contributing, update vscode-settings.json urls

- source/behavior/blocks/format/minecraft.block.json
- Changed the property name from `menu_category` to `category`
- Changed the category property from an object to a string
> Updated schema for the `menu_category` property

- source/general/manifest/manifest.2.json
Update script module names and versions that Minecraft currently accepts
> Update script module name and version (manifest)

- source/behavior/entities/format/events.json
- source/behavior/entities/format/minecraft.entity.json
- source/molang/boolean.json
Added missing "first_spawn_chance" in projectile behaviors.
> Added missing documentation on "first_spawn_chance" in projectile behaviors.

- source/behavior/entities/filters/filters/int_property.json
Updated int_property.json to the value type "integer" instead of "string"
> Fixed int_property.json to the integer value type.

- source/behavior/entities/filters/filters/has_equipment.json
Added missing "inventory" enum to the has_equipment component.
> Update has_equipment.json - Added "inventory" enum

- source/behavior/items/format/components/armor.json
- source/behavior/items/format/components/cooldown.json
- source/behavior/items/format/components/display_name.json
- source/behavior/items/format/components/durability.json
- source/behavior/items/format/components/fuel.json
- source/behavior/items/format/components/hand_equipped.json
- source/behavior/items/format/components/icon.json
- source/behavior/items/format/components/knockback_resistance.json
- source/behavior/items/format/components/on_use.json
- source/behavior/items/format/components/on_use_on.json
- source/behavior/items/format/components/projectile.json
- source/behavior/items/format/components/render_offsets.json
- source/behavior/items/format/components/shooter.json
- source/behavior/items/format/components/throwable.json
- source/behavior/items/format/components/weapon.json
- source/behavior/items/format/components/wearable.json
Add Examples to Item Components from mostly MS-Learn Website
> Add Item Examples

- source/behavior/entities/filters/filters/is_panicking.json
- source/behavior/entities/filters/filters/is_sprinting.json
Added `is_sprinting` and `is_panicking` entity filters.
> Add new entity filters

- source/behavior/entities/format/components/ageable.json
- source/behavior/entities/format/components/interact.json
Added `drop_item_slot` and `equip_item_slot` to `minecraft:interact` entity component
Added `interact_filters` to `minecraft:ageable` entity component
> Update entity components to 1.20.60

- package-lock.json
- package.json
Reverts Blockception/Minecraft-bedrock-json-schemas#207
> Revert "build(deps-dev): bump the all group with 4 updates"

- package-lock.json
- package.json
Reverts Blockception/Minecraft-bedrock-json-schemas#211
> Revert "build(deps): bump the all group with 3 updates"

- source/behavior/entities/format/minecraft.entity.json
> Spawn categories

- source/behavior/entities/format/types/event_object.json
Don't know if this is documented but it's in the bridge. autocomplete and it works in game
> - Add filters to event object

- source/behavior/recipes/types/base types/unlock.json
> Recipe unlocking

- source/behavior/items/format/components/icon.json
As per hatchi's comment on #221
> Fix icon for 1.20.70

- source/behavior/animations/animations.json
- source/resource/animations/actor_animation.json
Resolve #200 
Relevant conversation if required https://discord.com/channels/494194063730278411/771006131979812904/1222354978744565841
> Anim time update for bpa

- source/behavior/items/format/components/digger.json
> Fix digger

- source/general/manifest/manifest.2.json
> Update script manifest

- source/behavior/entities/format/events.json
> Make randomize and sequence have other event responses

- source/general/sound_event.json
> Remove sounds enum

- source/behavior/spawn_rules/components/brightness_filter.json
> Update brightness filter

- source/behavior/animation_controllers/animation_controller.json
- source/behavior/animations/animations.json
- source/behavior/blocks/blocks.json
- source/behavior/dialogue/dialogue.json
- source/behavior/entities/entities.json
- source/behavior/items/items.json
- source/behavior/spawn_rules/spawn_rules.json
- source/resource/animation_controllers/animation_controller.json
- source/resource/animations/actor_animation.json
- source/resource/attachables/attachables.json
- source/resource/entity/entity.json
- source/resource/render_controllers/render_controllers.json
> Add snippets

- source/behavior/items/format/components/max_stack_size.json
- source/resource/particles/particles.json
> Closing up issues I'd opened before

- source/behavior/blocks/format/components/custom_components.json
- source/behavior/blocks/format/minecraft.block.json
- source/behavior/items/format/components/custom_components.json
- source/behavior/items/format/minecraft.item.json
https://learn.microsoft.com/en-us/minecraft/creator/documents/customcomponents?view=minecraft-bedrock-stable
> Custom components

- source/behavior/blocks/format/components/entity_fall_on.json
- source/behavior/blocks/format/components/tick.json
- source/behavior/blocks/format/minecraft.block.json
- source/behavior/blocks/format/triggers/queued_ticking.json
https://discord.com/channels/523663022053392405/1145868241634345004/1228744807816499220
> Additional block custom component stuff

- source/resource/models/entity/1.16.0/model_entity.json
- source/resource/models/entity/1.8.0/model_entity.json
> Update geometry identifier to allow for : in it 

- vscode-settings.json
Fixis: https://github.com/Blockception/VSCode-Bedrock-Development-Extension/issues/680
> adding tigther schema checks for entities

- source/behavior/entities/format/components.json
- source/behavior/entities/format/components/dimension_bound.json
1. Added dimension_bound.json with documentation for minecraft:dimension_bound component.
2. Edited components.json to include "minecraft:dimension_bound" reference for the auto-complete list.
> Addded "minecraft:dimension_bound":{} with documentation.

- source/behavior/entities/format/components/damage_sensor.json
> fix: damage_sensor | triggers | deals_damage accept string only

- source/behavior/entities/format/behaviors/float_wander.json
> Updated float_wander

- source/behavior/entities/filters/filters.json
- source/behavior/entities/filters/filters/is_vehicle_family.json
Apparently, they were not done with 1.21.90
> - Added is_vehicle_family filter
