source/behavior/entities/1.8.0/components/minecraft.spell_effects.json
Although most documentation suggests this is only a string, the vanilla behaviour pack `items/honey_bottle.json` demonstrates that arrays of strings are also valid. I've tested this, and can confirm multiple effects are correctly removed when multiple strings are provided in the array.
=> Allow string array for minecraft:spell_effects remove_effect.

source/behavior/entities/format/components/timer.json
- Update the example to use the correct event schema. Previously it was using a string and not the event schema.
- Wrote documentation for the `value` field in `random_time_choices`
=> Modify timer schema

source/behavior/entities/format/behaviors/avoid_block.json, source/behavior/entities/format/behaviors/lay_egg.json, source/behavior/entities/format/behaviors/move_to_liquid.json, source/behavior/entities/format/behaviors/move_to_poi.json, source/behavior/entities/format/behaviors/summon_entity.json, source/behavior/entities/format/behaviors/work.json, source/resource/particles/components/particle_appearance_billboard.json
Added constraints:
- `active_time` in minecraft:behavior.work component must be greater than 0
Added enums:
- `target_selection_method` in minecraft:behavior.avoid_block was missing `random`
- `target_materials_above_block` in minecraft:behavior.lay_egg
- `material_type` in minecraft:behavior.move_to_liquid
- `poi_type` in minecraft:behavior.move_to_poi
- `shape` in minecraft:behavior.summon_entity
Also added `direction` field to `minecraft:particle_appearance_billboard` particle component.
=> Add various enums and constraints and direction property in particle

README.md
Capitalize the string `JSON` whenever it appears (except URLs). Some other renditions were `Json` and `json`.
Consolidate both Contributing headings to one.
Capitalize `## Behavior files`.
Add some missing punctuation.
=> Fix README inconsistencies

source/resource/blocks.json
Fixed "format_version" in blocks.json + changes.
Attempted to resolve the bug https://github.com/Blockception/Minecraft-bedrock-json-schemas/issues/156 by adding support for array type.
Also added some documentation to a few of the block.json keys for Gamma, and Carried Textures.
=> Fixed "format_version" in blocks.json + changes.

source/behavior/entities/format/components/projectile.json
Added missing "first_spawn_chance" information to the projectile behavior inside of "minecraft:projectile" key inside of "on_hit" key inside of "spawn_chance" key.
I plan on doing a few more small pull requests here and there when I'm able.
=> Added missing "first_spawn_chance" information.

source/behavior/entities/format/components/knockback_resistance.json
The minecraft:ender_dragon uses a value that is 100x higher than 1.0, I've increased the max cap on this component to at least that amount.
Found in the vanilla behavior pack.
ender_dragon.json
```
"minecraft:knockback_resistance": {
"value": 100,
"max": 100
}
```
Also added another example:
{
"value": 100
}
=> Updated knockback_resistance component's max value

source/behavior/entities/format/components/physics.json
- Updated physics.json with new variable "push_towards_closest_space" and updated documentation to be consistent, added another example.
- The "push_towards_closest_space" is found on entities/player.json in the behavior pack in the version 1.19.50;
=> minecraft:physics - added "push_towards_closest_space"

source/behavior/entities/format/components/attack_cooldown.json, source/behavior/entities/format/components/attack_damage.json, source/behavior/entities/format/components/balloonable.json, source/behavior/entities/format/components/boostable.json, source/behavior/entities/format/components/follow_range.json, source/behavior/entities/format/components/health.json, source/behavior/entities/format/components/hide.json, source/behavior/entities/format/components/is_stackable.json, source/behavior/entities/format/components/lava_movement.json, source/behavior/entities/format/components/player.exhaustion.json, source/behavior/entities/format/components/player.experience.json, source/behavior/entities/format/components/player.level.json, source/behavior/entities/format/components/player.saturation.json, source/behavior/entities/format/components/shooter.json, source/behavior/entities/format/components/teleport.json, source/behavior/entities/format/components/underwater_movement.json, source/behavior/items/format/components/durability.json, source/behavior/items/format/components/entity_placer.json
Mainly under the Entity Components
- Updated descriptions
- Fixed typos
- Corrected data types
- Added 'default' where needed
- Added missing parameters
- Removed invalid parameters
- Added and/or updated examples
Used information from MS-Learn component pages.  
* *Except for entity_placer.json, added logical title and description to the items-array info for the dispense_on/use_on*
=> Updating Undocumented

source/resource/textures/nine_slice.json, vscode-settings.json
This Pull Request introduces the 9-Slice schema for textures, a technique that allows creators to make textures that are not only scalable but also minimized in size. The 9-Slice method divides the image into nine sections:
- 4 corners, that are not scaled
- 4 sides, that are scaled in one axis
- center part, that is scaled in both X and Y axis
More detailed explanation on wiki: https://en.wikipedia.org/wiki/9-slice_scaling
=> Add 9Slice schema

source/behavior/blocks/format/components/geometry.json, source/behavior/blocks/format/components/unit_cube.json
Modified `minecraft:geometry` block component to include `minecraft:geometry.full_block` as a constant.
=> Added full_cube constant to block geometry

source/behavior/entities/format/components/entity_sensor.json
Updated `entity_sensor`'s JSON schema to  change from 1.20.60.21 beta.
From changelog:
- The "entity_sensor" component now supports multiple "subsensors":
- "event", "require_all", "minimum_count", "maximum_count", "range" and "event_filter" are now individually configurable fields of each subsensor
- Subsensors also have a new "cooldown" field, which defines how often each subsensor should sense for entities
- All these changes require a "format_version" of 1.20.60 or higher
=> Update entity_sensor's schema to 1.20.60

source/resource/particles/components/particle_appearance_billboard.json, source/resource/particles/components/particle_motion_collision.json, source/resource/particles/particles.json
This PR updates particle schemas:
- Added additive material to example materials
- Added missing `facing_camera_mode` values
- Added `sequence`, `randomize`, `weight`, `log` and `expression` fields to the particle event schema
=> Update particle schemas

source/behavior/recipes/types/base types/item.json, source/behavior/recipes/types/furnace.json
=> Update recipes to add unlocking to furnace and fix #226

source/behavior/blocks/format/minecraft.block.json, source/behavior/blocks/format/states/enum.json, source/behavior/blocks/format/states/integer_range.json
- Updated the description of block states, removing the [EXPERIMENTAL] notice.
- Removed the following non-existent parameters: `is_experimental`, `register_to_creative_menu`.
- Made the types for valid state values stricter
- All enum array items must be distinct and of the same type.
- Enum arrays must not be longer than 16 items and must have at least 1 item.
- Expanded documentation of integer ranges, adding the `values` property with its `min` and `max` parameters.
=> Update block description

source/behavior/blocks/format/traits/placement_direction.json
- `y_rotation_offset` can now be any number that is a multiple of 90.
- Enabled states must be distinct.
=> Update minecraft:placement_direction block trait

source/general/vanilla/creative_category.json
It doesn't exist and will result in a content error if used.
=> Remove "commands" Menu Category

source/compress_specification.json, source/resource/textures/texture_list.json, source/resource/textures/textures_list.json, vscode-settings.json
Added an "s" to match the following pages:
- [Getting Started with Deferred Lighting | Microsoft Learn](https://learn.microsoft.com/en-us/minecraft/creator/documents/deferredlighting?view=minecraft-bedrock-stable#deferred-lighting-json-files)
- [textures_list.json | Bedrock Wiki](https://wiki.bedrock.dev/concepts/textures-list)
=> Correct name of "textures_list.json"

source/behavior/items/format/components/allow_off_hand.json, source/behavior/items/format/components/can_destroy_in_creative.json, source/behavior/items/format/components/display_name.json, source/behavior/items/format/components/glint.json, source/behavior/items/format/components/hand_equipped.json, source/behavior/items/format/components/hover_text_color.json, source/behavior/items/format/components/icon.json, source/behavior/items/format/components/liquid_clipped.json, source/behavior/items/format/components/max_stack_size.json, source/behavior/items/format/components/should_despawn.json, source/behavior/items/format/components/stacked_by_data.json, source/behavior/items/format/components/use_animation.json
Many item components also support a format similar to `"minecraft:component": true` rather than `"minecraft:component": { "value": true }`
=> Support single values for item components

source/behavior/lighting/atmospherics.json, source/behavior/lighting/color.json, source/behavior/lighting/global.json, source/compress_specification.json, vscode-settings.json
=> Adding deferred lightning schemas

source/behavior/blocks/format/components/material_instances.json
Was mentioned in 1.20.70's changelogs but has apparently existed prior to that.
=> Add new block material

source/resource/textures/terrain_texture.json
CHANGELOG:
Added description for the "num_mip_levels" property, describing its function in setting mipmap levels.
Added description for the "padding" property, describing its function in adding buffer space to prevent texture bleeding.
I moved my edits into the correct directory.
=> Fixed terrain_texture.json edits and added descriptions on  "num_mip_levels" and "padding"

source/behavior/recipes/types/recipe_shapeless.json
Shapeless recipes in 1.21.30 don't seem to support not using any array for ingredients. This changes that, reducing confusion as to why recipes might not be working, especially when only using one ingredient, and getting rid of the annoying "Matches multiple schemas when only one must validate." when using the correct syntax.
Fixed after first PR that edited compiled files
=> Fix ingredients in shapeless recipe schema

README.md, source/compress_specification.json, source/resource/biomes/biomes.json, source/resource/biomes/format/components/fog_appearance.json, source/resource/biomes/format/components/sky_color.json, source/resource/biomes/format/components/water_appearance.json, source/resource/biomes/format/minecraft.client_biome.json, vscode-settings.json
=> Add client biome schema

source/resource/biomes/biomes.json, source/resource/biomes/format/components/foliage_appearance.json, source/resource/biomes/format/components/grass_appearance.json, source/resource/biomes/format/minecraft.client_biome.json
Added in Preview 1.21.60.25 https://bedrock.dev/docs/beta/Client%20Biomes
=> Add foliage and grass appearance client biome components

source/resource/textures/texture_set.json, vscode-settings.json
- Require that `format_version` is set to one of the supported values: `1.16.100` or `1.21.30`.
- Added support for the `metalness_emissive_roughness_subsurface` parameter.
- Incompatible parameters can no longer be specified together (`heightmap` and `normal`, `metalness_emissive_roughness` and `metalness_emissive_roughness_subsurface`).
- Array color values are now validated correctly
=> Improve texture set schema

source/behavior/entities/format/events.json
Currently `first_valid` in entity events is an object. This PR makes it into a proper array.
The reformat was automatically caused on save by prettier.
=> Make `first_valid` an array

source/resource/models/entity/1.21.0/model_entity.json
Add `uv_rotation` to model_entity.json schema for 1.21.0.
Source: https://learn.microsoft.com/en-us/minecraft/creator/reference/content/schemasreference/schemas/minecraftschema_geometry_1.21.0?view=minecraft-bedrock-stable
=> Add uv_rotation to model_entity 1.21.0

source/behavior/features/features/minecraft.geode_feature.json, source/behavior/features/features/minecraft.growing_plant_feature.json, source/behavior/features/features/minecraft.multiface_feature.json, source/behavior/features/features/minecraft.nether_cave_carver_feature.json, source/behavior/features/features/minecraft.single_block_feature.json, source/behavior/features/features/minecraft.structure_template_feature.json, source/behavior/features/features/minecraft.tree_feature.json, source/behavior/features/features/minecraft.vegetation_patch_feature.json
This PR removes incorrect `type` definition from block references as well as fixes array + weighted schema in single_block_feature
=> fix: remove incorrect type definitions in features

source/resource/fog/fog.json
Added required properties to `transition_fog` settings. Attempting to create a `transition_fog` without these required properties makes the fog fail to load.
=> feat: adding required properties to fog/transition_fog
